### ISSUE TITLE
Website suggestion

### ISSUE THREAD

**Issue by lambdamoses** [cantin-ortiz/molecular-atlas#1]
Hi, thanks for this amazing resource! I downloaded the gene count matrix and started exploring the data. Your website says,

> Parsing the expression matrix might be long due to its size.
> If you are using R, the .tsv files can be parsed using the following instruction:
> read.table(path, sep = '\t', stringsAsFactors = F, header = T, row.names = 1)

Just a suggestion: Yes, this fat data frame will take a while to load with base R. But I used [`vroom`](https://vroom.r-lib.org/index.html), which only took like 3 seconds. I think this suggestion, or using `data.table::fread()`, would be useful to people who are frustrated by how long it takes to load the data.

**Comment by cantin-ortiz** [comment]
Hi, thank you for your interest in our data!
This is a very good point, using lazy loading would be less frustrating. I updated the description on the website with your recommendation, thanks a lot for this useful feedback.
